#==============================================================#
#  kitty.conf                                                   #
#  Terminal configuration                                      #
#  https://sw.kovidgoyal.net/kitty/conf/                        #
#==============================================================#

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#
#//////  THEME  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#

include ~/.local/share/kitty-themes/themes/Dracula.conf  # pick your theme

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#
#//////  FONT  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 11.0

#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#
#//////  QUALITY OF LIFE  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#
#\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\#

enable_audio_bell no
cursor_shape beam
scrollback_lines 10000
confirm_os_window_close 0
background_opacity 0.92

# Helpful kittens
map ctrl+shift+o  kitten hints --type path --type url
map ctrl+shift+c  copy_to_clipboard
map ctrl+shift+v  paste_from_clipboard
map ctrl+shift+u  kitten unicode_input
map ctrl+shift+s  kitten ssh
